### ISSUE TITLE
AttributeError: type object 'MongoengineConnectionField' has no attribute 'name' OR AttributeError: type object 'NoneType' has no attribute 'name'

### ISSUE THREAD

**Issue by anilwarbhe** [riverfr0zen/graphene-mongo-extras#1]
If I have a info of "Highscore" info=ListField(EmbeddedDocumentField(PlaythruInfo)) insted of     info = EmbeddedDocumentField(PlaythruInfo) it thows "AttributeError: type object 'NoneType' has no attribute 'name'"
class HighScore(Document):
    player = StringField()
    score = IntField()
    recorded = DateTimeField()
    info = EmbeddedDocumentField(PlaythruInfo)

use 
info=ListField(EmbeddedDocumentField(PlaythruInfo))

and it will throw an error. Please help.

**Comment by riverfr0zen** [comment]
Hi Anil, 

It's a deficiency in `convert_for_lookup` in `filtering.utils`. Since the software is still in an alpha state, there will probably be some uncovered cases like this. 

Thanks for the bug report -- I will look into it, but it may be a week or so as I have some pressing deadlines. You are welcome to submit a PR if you want to take a stab.

**Comment by riverfr0zen** [comment]
This issue should be fixed in the latest commit. Leaving this open for a while for comments/questions. @anilwarbhe
