### ISSUE TITLE
Query takes too much time (more than 5 minutes to retrieve first 10 documents)

### ISSUE THREAD

**Issue by anilwarbhe** [riverfr0zen/graphene-mongo-extras#6]
In "products" collection I have around 3000000 documents in a collection and I want to paginate it.
I am using the following query:

{
allProducts(first:10){
edges{
node{
brandname
}
cursor
}
pageInfo{
hasPreviousPage
hasNextPage
startCursor
endCursor
}
}
}
and it either fails or takes too much time to fetch the documents. Please tell me what I am doing wrong.

**Comment by riverfr0zen** [comment]
@anilwarbhe Is this an issue specific to graphene-mongo-extras, or graphene-mongo in general? From what you posted, I can't see anything specific about graphene-mongo-extras there, it just looks like a query to a regular Connection.

If it's not specific to graphene-mongo-extras, I suggest posting the issue to the graphene-mongo project instead. Also, I suggest adding some more information, such as your models, and type schema, your mongodb setup (RAM, etc), otherwise people won't know how to help you.

**Comment by anilwarbhe** [comment]
Thank you so much for your reply. This is a generic error and definitely not related to extras. But I wonder how come no one noticed it yet. The query works perfectly well for only few thousand records. But it it exceeds some 5000 documents or so in the collection. it takes 2 to 3 minutes t resolve the data.
I have asked it it graphene mongo.

**Comment by riverfr0zen** [comment]
Interesting, I look forward to seeing the responses there. Closing here for now.
